# To ask the user and print  numbers in such way that repitition is not allowed. 
nums = set()
num1 = input("Enter your number:")
nums.add(int(num1))
num2 = input("Enter your number:")
nums.add(int(num2))
num3 = input("Enter your number:")
nums.add(int(num3))
num4 = input("Enter your number:")
nums.add(int(num4))
num5= input("Enter your number:")
nums.add(int(num5))
num6 = input("Enter your number:")
nums.add(int(num6))
num7 = input("Enter your number:")
nums.add(int(num7))
num8 = input("Enter your number:")
nums.add(int(num8))

print(nums)