d = {}
name1 = input("Enter your name:")
s1 = input("Enter your fav language:")
d.update({name1:s1})
name2 = input("Enter your name:")
s2 = input("Enter your fav language:")
d.update({name2:s2})
name3 = input("Enter your name:")
s3 = input("Enter your fav language:")
d.update({name3:s3})
name4 = input("Enter your name:")
s4 = input("Enter your fav language:")
d.update({name4:s4})
print(d)